global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#  - job_name: 'actuator'
#    static_configs:
#      - targets: ['host.docker.internal:9092'] # kafka broker exposed on localhost (host.docker.internal) on port 9092
#      - targets: ['host.docker.internal:8080'] # conduktor console exposed on localhost (host.docker.internal) on port 8080

#172.17.0.1 same as host.docker.internal
